server.port=8080

spring.application.name=API-GATEWAY

# Route 1: Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Route 2: Student Service
spring.cloud.gateway.routes[1].id=student-service
spring.cloud.gateway.routes[1].uri=lb://STUDENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/students/**
spring.cloud.gateway.routes[1].filters[0]=JwtGatewayFilter

# Route 3: Attendance Service
spring.cloud.gateway.routes[2].id=attendance-service
spring.cloud.gateway.routes[2].uri=lb://ATTENDANCE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/attendance/**
spring.cloud.gateway.routes[2].filters[0]=JwtGatewayFilter

# Route 4: Result Service
spring.cloud.gateway.routes[3].id=result-service
spring.cloud.gateway.routes[3].uri=lb://RESULT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/results/**
spring.cloud.gateway.routes[3].filters[0]=JwtGatewayFilter

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=12345678901234567890123456789012345678901234567890