server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**
          filters:
            - JwtGatewayFilter

        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/attendance/**
          filters:
            - JwtGatewayFilter

        - id: result-service
          uri: lb://RESULT-SERVICE
          predicates:
            - Path=/api/results/**
          filters:
            - JwtGatewayFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 12345678901234567890123456789012345678901234567890
